language: scala
scala:
    - 2.10.3
jdk:
    - oraclejdk8
script:
  - 'sbt testOnly ThreadOverflowTest'
# wait for update on sbt-coveralls plugin
#    - "sbt clean coverage test"
#after_success:
#    - "sbt coveralls"
